//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4_CreatureGenerator.Pages {
    
    
    public partial class Home {
        
        protected System.Web.UI.WebControls.Content Header_Content;
        
        protected System.Web.UI.WebControls.Button Test;
        
        protected System.Web.UI.WebControls.Content Menu_Content;
        
        protected System.Web.UI.WebControls.Button Test3;
        
        protected System.Web.UI.WebControls.Content Body_Content;
        
        protected System.Web.UI.WebControls.Button Test1;
        
        protected System.Web.UI.WebControls.Content Footer_Content;
        
        protected System.Web.UI.WebControls.Button Test2;
    }
}
